name: event_management_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^8.0.5
  google_fonts: ^4.0.4
  persistent_bottom_nav_bar: ^5.0.2
  pushable_button: ^0.0.2
  salomon_bottom_bar: ^3.3.2
  searchbar_animation: ^0.0.4
  switcher_button: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/images/

fonts:
  - family: Poppins
    fonts: 
      - asset: fonts/Poppins-ExtraLight.ttf